# Generated by Django 3.1.3 on 2020-11-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=250)),
                ('photo_raw', models.BinaryField()),
                ('photo_embed', models.TextField()),
            ],
        ),
    ]
