# Generated by Django 3.1.3 on 2020-11-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finuser',
            name='photo_embed',
            field=models.ImageField(max_length=254, upload_to='photos'),
        ),
    ]
