# Generated by Django 3.1.3 on 2020-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201128_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finuser',
            name='photo_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finuser',
            name='photo_raw',
            field=models.BinaryField(),
        ),
    ]
